// I didn't see an enumerator for the Resource Types in AWS, so I created one. 
// www.ericperron.com 2021

export enum TagResourceType {

    client_vpn_endpoint  = "client-vpn-endpoint ",
    customer_gateway = "customer-gateway",
    dedicated_host = "dedicated-host",
    dhcp_options = "dhcp-options",
    egress_only_internet_gateway = "egress-only-internet-gateway",
    elastic_ip = "elastic-ip",
    elastic_gpu  = "elastic-gpu ",
    export_image_task = "export-image-task",
    export_instance_task = "export-instance-task",
    fleet = "fleet",
    fpga_image = "fpga-image",
    host_reservation = "host-reservation",
    image = "image",
    import_image_task = "import-image-task",
    import_snapshot_task = "import-snapshot-task",
    instance = "instance",
    internet_gateway = "internet-gateway",
    key_pair = "key-pair",
    launch_template = "launch-template",
    local_gateway_route_table_vpc_association = "local-gateway-route-table-vpc-association",
    natgateway = "natgateway",
    network_acl = "network-acl",
    network_interface = "network-interface",
    network_insights_analysis = "network-insights-analysis",
    network_insights_path = "network-insights-path",
    placement_group = "placement-group",
    reserved_instances = "reserved-instances",
    route_table = "route-table",
    security_group = "security-group",
    snapshot = "snapshot",
    spot_fleet_request = "spot-fleet-request",
    spot_instances_request = "spot-instances-request",
    subnet = "subnet",
    traffic_mirror_filter = "traffic-mirror-filter",
    traffic_mirror_session = "traffic-mirror-session",
    traffic_mirror_target = "traffic-mirror-target",
    transit_gateway = "transit-gateway",
    transit_gateway_attachment = "transit-gateway-attachment",
    transit_gateway_connect_peer = "transit-gateway-connect-peer",
    transit_gateway_multicast_domain = "transit-gateway-multicast-domain",
    transit_gateway_route_table = "transit-gateway-route-table",
    volume = "volume",
    vpc = "vpc",
    vpc_peering_connection = "vpc-peering-connection",
    vpn_connection  = "vpn-connection ",
    vpn_gateway = "vpn-gateway",
    vpc_flow_log = "vpc-flow-log",    
}